# This config is used when build_all.yml is triggered by a release
# Refer: .github/workflows/build_all.yml
# https://github.com/iqfareez/iium_schedule/actions/workflows/build_all.yml

# Flutter channel: `stable` or `beta` or `master`
flutter_channel: stable

# build target. Set `true` or `false`
build_for:
  windows: true
  android: true
  web: false
